```{r}
p <- c(0,0)
f <- function(p){
  x <- p[1]
  y <- p[2]
  return(-x^2 -x^2*y^2 -2*x*y +2*x +2)
}
f_x <- function(p){
  x <- p[1]
  y <- p[2]
  return(-2*x -2*x*y^2 -2*y +2)
}
f_y <- function(p){
  x <- p[1]
  y <- p[2]
  return(-2*x^2*y-2*x)
}
f_xy <- function(p){
  x <- p[1]
  y <- p[2]
  return(-4*x*y-2)
}
f_xx <- function(p){
  x <- p[1]
  y <- p[2]
  return(-2 -2*y^2)
}
f_yy <- function(p){
  x <- p[1]
  y <- p[2]
  return(-2*x^2)
}
get_gradient <- function(p){
  return(c(f_x(p), f_y(p)))
}
get_hessian <- function(p){
  hess <- matrix(c(f_xx(p), f_xy(p), f_xy(p), f_yy(p)), ncol=2)
  return(hess)
}

get_hessian(c(0,0))
get_gradient(c(0,0))
f(c(0,0))
```


```{r}
f <- function(x,y){
  return(-x^2-x^2*y^2-2*x*y+2*x+2)
}

x <- -3:3
length(x)
y <- -3:3
z <-  matrix(f(x,y), nrow = 21, ncol = 21)
contour(x, y, z)

```

```{r}
newton <- function(x, epsilon){
  #x is you starting vector
  dist <- 999
  
  while(dist > epsilon){
    gp <- get_gradient(x)
    gpp <- get_hessian(x)
    x_next <- x - solve(gpp)%*%gp
    dist <- sum((x-x_next)*(x-x_next))
    x <- x_next
  }
  return(x)
}
p1 <- c(2,0)
p2 <- c(-1,-2)
p3 <- c(0,1)
p4 <- c(10,-10)
epsilon <- 1E-8
newton(p1, epsilon)
newton(p2, epsilon)
newton(p3, epsilon)
newton(p4, epsilon)

```



